### ISSUE TITLE
Observations?

### ISSUE THREAD

**Issue by jogboms** [xsahil03x/fancy_on_boarding#2]
@xsahil03x Just wondering though,
Did you by any chance see this?
https://github.com/aagarwal1012/IntroViews-Flutter

**Comment by xsahil03x** [comment]
Hey @jogboms i haven't seen this library.

But the original code is from : https://github.com/matthew-carroll/flutter_ui_challenge_material_page_reveal

And i had given full credits to him in my starting lines. His design was awesome and i also used that in one of my project. But when i need it again, instead of copying the whole code i tried to convert that into a library for my easy use. Thus also shared with all of you. :smile:
